# Generated by Django 2.2.5 on 2021-05-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('winScore', models.IntegerField()),
                ('loseScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('games_played', models.IntegerField()),
                ('match_points', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('points', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('current_streak', models.IntegerField()),
                ('goals_in_a_game', models.IntegerField()),
                ('assists_in_a_game', models.IntegerField()),
                ('points_in_a_game', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_player', to='Statistics.Player')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_in', to='Statistics.Game')),
                ('goalie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalie_player', to='Statistics.Player')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_player', to='Statistics.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_one',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_1', to='Statistics.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_two',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_2', to='Statistics.Player'),
        ),
    ]
